#!/bin/bash
#mount "/dev/disk/by-label/XenServer\x20Tools" /mnt
ls /dev
mount /dev/{{ device }} /mnt
cd /mnt/Linux
./install.sh -n

mkdir -p /root/.ssh/
echo "{{ pubkey }}" >> /root/.ssh/authorized_keys
chmod  700 /root/.ssh
chmod -R 600 /root/.ssh/*
