#!/bin/bash
#mount "/dev/disk/by-label/XenServer\x20Tools" /mnt
mount /dev/sr0 /mnt
cd /mnt/Linux
./install.sh -n

mkdir /root/.ssh/
echo "{{ pubkey }}" >> /root/.ssh/authorized_keys
chmod  700 /root/.ssh
chmod -R 600 /root/.ssh/*

